version: '3'

services:
  selenium-hub:
     image:selenium/hub:latest
     ports:
      -"4442-4444:4442-4444"
     networks:
      - grid3
      
  node-chrome:
     image: selenium/node-chrome:latest
     environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
     networks:
        - grid3
        
    node-firefox:
     image: selenium/node-firefox:latest
     environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
     networks:
        - grid3             
        
networks:
  grid3:
    driver: bridge        